### PR TITLE
Problem: (fix #78) `check-validator-up.sh` does not work for more the…

### LINKED ISSUE #78: Problem: `check-validator-up.sh` does not work for more then 100 active validators
```bash
ADDRESS=$(curl --max-time 10 -sSL "${TENDERMINT_URL}/validators?per_page=300" | jq -r --arg PUBKEY "${PUBKEY}" '.result.validators[] | select(.pub_key.value == $PUBKEY) | .address')
```
See [link](https://github.com/crypto-com/chain-docs/blob/5a8b8cf377a078042e02d8fb9ac8947dd0e03575/docs/getting-started/assets/signature_checking/check-validator-up.sh#L53). It would not cover the case for more than 100 validators as the maximum result per page is 100.

### PR DESCRIPTION
**Pull request by allthatjazzleo**
…n 100 active validators

Solution: fix script

```bash
./check-validator-up.sh --tendermint-url https://testnet-croeseid.crypto.com:26657 --pubkey xxxxxx --bechpubkey tcrocnclconspub1zcjduepqc9krg77mt9c4n84l7dezv4n0us99mm2wfqud5vk8w5lldv8e03eqv5s3we
```
it also allow Bech32 Validator Consensus instead of just tendermint/PubKeyEd25519 if `--bechpubkey` is provided.

### CODE REVIEW

File: docs/getting-started/assets/signature_checking/check-validator-up.sh [hunk 1]
```diff
@@ -38,29 +42,50 @@ while [[ $# > 0 ]]; do
...
 if [[ -z "${PUBKEY}" ]]; then
 	echoerr "Missing --pubkey {base64 encoded Tendermint public key}"
-	exit 1
 fi
 set -u
-ADDRESS=$(curl --max-time 10 -sSL "${TENDERMINT_URL}/validators?per_page=300" | jq -r --arg PUBKEY "${PUBKEY}" '.result.validators[] | select(.pub_key.value == $PUBKEY) | .address')
+NUM=1
+while true; do
+    ERR=$(curl -sSL "${TENDERMINT_URL}/validators?per_page=100&page=${NUM}" | jq -r .error)
+    if [[ $ERR == "null" ]]; then
```
Comment (tomtau) [inline docs/getting-started/assets/signature_checking/check-validator-up.sh:70]: null is returned if it's an empty page?

Comment (allthatjazzleo) [reply docs/getting-started/assets/signature_checking/check-validator-up.sh:70]: null is returned if it is still within pagination.
it is not null when tendermint rpc return
`bash
{
  "jsonrpc": "2.0",
  "id": -1,
  "error": {
    "code": -32603,
    "message": "Internal error",
    "data": "page should be within [1, 2] range, given 3"
  }
}
`
